import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

import "./globals.css";
import NavBar from "./components/NavBar";
import { AuthProvider } from "./components/Authprovider";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "FuseBlog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
        <html lang="en">
          <body className={`${inter.className} max-w-7xl mx-auto px-4 sm:px-6 lg:px-8`}>
            <NavBar/>
            {children}
            <Footer />
          </body>
        </html>
    </AuthProvider>
  );
}
